name: Track Visitor

on:
  push: # Menjalankan script setiap kali ada push ke repository
    branches:
      - main # Ganti dengan nama branch utama Anda jika berbeda
  workflow_dispatch: # Memungkinkan menjalankan secara manual dari tab Actions

jobs:
  log-visitors:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Track Visitor
      run: |
        echo "Visitor on $(date)" >> visitors.log
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add visitors.log
        git commit -m "Track visitor on $(date)"
        git push
